// Minimal wire contract for the cmdop-care MCP artifact.
//
// This is a DELIBERATELY TRIMMED subset of the private cmdop_go monorepo's
// `cmdop.agent.v1` proto package (proto/agentv1/service/{care,ai_agent,session}.proto).
// It carries only the messages and RPCs the 4 read-only tools in this
// artifact need:
//   - AiAgentService.GetMachineCare              (care_status)
//   - AiAgentService.RunMachineCareDiagnostic     (care_diagnose)
//   - SessionService.ListSessions                  (list_machines)
//
// It intentionally OMITS every mutation / exec / delegation RPC (RunAgent,
// CancelAgent, Extract, CreateSession, CloseSession, and the Care action
// propose/decision messages) — this artifact never calls them and does not
// even generate stubs for them, so there is no code path that could.
//
// Wire-compatible with the private relay: field numbers below match the
// source-of-truth proto exactly, so this client interoperates with any
// cmdop relay speaking cmdop.agent.v1, but this file is maintained here
// independently (it is not regenerated from the private monorepo).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/care.proto

package carepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SessionStatus int32

const (
	SessionStatus_SESSION_STATUS_UNSPECIFIED SessionStatus = 0
	SessionStatus_SESSION_STATUS_ONLINE      SessionStatus = 1
	SessionStatus_SESSION_STATUS_OFFLINE     SessionStatus = 2
)

// Enum value maps for SessionStatus.
var (
	SessionStatus_name = map[int32]string{
		0: "SESSION_STATUS_UNSPECIFIED",
		1: "SESSION_STATUS_ONLINE",
		2: "SESSION_STATUS_OFFLINE",
	}
	SessionStatus_value = map[string]int32{
		"SESSION_STATUS_UNSPECIFIED": 0,
		"SESSION_STATUS_ONLINE":      1,
		"SESSION_STATUS_OFFLINE":     2,
	}
)

func (x SessionStatus) Enum() *SessionStatus {
	p := new(SessionStatus)
	*p = x
	return p
}

func (x SessionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_care_proto_enumTypes[0].Descriptor()
}

func (SessionStatus) Type() protoreflect.EnumType {
	return &file_proto_care_proto_enumTypes[0]
}

func (x SessionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionStatus.Descriptor instead.
func (SessionStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_care_proto_rawDescGZIP(), []int{0}
}

type CareCapabilities struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	RemoteDiagnosticSupported bool                   `protobuf:"varint,1,opt,name=remote_diagnostic_supported,json=remoteDiagnosticSupported,proto3" json:"remote_diagnostic_supported,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *CareCapabilities) Reset() {
	*x = CareCapabilities{}
	mi := &file_proto_care_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CareCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CareCapabilities) ProtoMessage() {}

func (x *CareCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_proto_care_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CareCapabilities.ProtoReflect.Descriptor instead.
func (*CareCapabilities) Descriptor() ([]byte, []int) {
	return file_proto_care_proto_rawDescGZIP(), []int{0}
}

func (x *CareCapabilities) GetRemoteDiagnosticSupported() bool {
	if x != nil {
		return x.RemoteDiagnosticSupported
	}
	return false
}

type CareFact struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Code             string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Value            int64                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	Unit             string                 `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`
	Coverage         string                 `protobuf:"bytes,4,opt,name=coverage,proto3" json:"coverage,omitempty"`
	ReasonCode       string                 `protobuf:"bytes,5,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	CapturedAtUnixMs int64                  `protobuf:"varint,6,opt,name=captured_at_unix_ms,json=capturedAtUnixMs,proto3" json:"captured_at_unix_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CareFact) Reset() {
	*x = CareFact{}
	mi := &file_proto_care_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CareFact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CareFact) ProtoMessage() {}

func (x *CareFact) ProtoReflect() protoreflect.Message {
	mi := &file_proto_care_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CareFact.ProtoReflect.Descriptor instead.
func (*CareFact) Descriptor() ([]byte, []int) {
	return file_proto_care_proto_rawDescGZIP(), []int{1}
}

func (x *CareFact) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CareFact) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *CareFact) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *CareFact) GetCoverage() string {
	if x != nil {
		return x.Coverage
	}
	return ""
}

func (x *CareFact) GetReasonCode() string {
	if x != nil {
		return x.ReasonCode
	}
	return ""
}

func (x *CareFact) GetCapturedAtUnixMs() int64 {
	if x != nil {
		return x.CapturedAtUnixMs
	}
	return 0
}

type CareFactDomain struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Code             string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Coverage         string                 `protobuf:"bytes,2,opt,name=coverage,proto3" json:"coverage,omitempty"`
	ReasonCode       string                 `protobuf:"bytes,3,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	CapturedAtUnixMs int64                  `protobuf:"varint,4,opt,name=captured_at_unix_ms,json=capturedAtUnixMs,proto3" json:"captured_at_unix_ms,omitempty"`
	Facts            []*CareFact            `protobuf:"bytes,5,rep,name=facts,proto3" json:"facts,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CareFactDomain) Reset() {
	*x = CareFactDomain{}
	mi := &file_proto_care_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CareFactDomain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CareFactDomain) ProtoMessage() {}

func (x *CareFactDomain) ProtoReflect() protoreflect.Message {
	mi := &file_proto_care_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CareFactDomain.ProtoReflect.Descriptor instead.
func (*CareFactDomain) Descriptor() ([]byte, []int) {
	return file_proto_care_proto_rawDescGZIP(), []int{2}
}

func (x *CareFactDomain) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CareFactDomain) GetCoverage() string {
	if x != nil {
		return x.Coverage
	}
	return ""
}

func (x *CareFactDomain) GetReasonCode() string {
	if x != nil {
		return x.ReasonCode
	}
	return ""
}

func (x *CareFactDomain) GetCapturedAtUnixMs() int64 {
	if x != nil {
		return x.CapturedAtUnixMs
	}
	return 0
}

func (x *CareFactDomain) GetFacts() []*CareFact {
	if x != nil {
		return x.Facts
	}
	return nil
}

type CareFactsSnapshot struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion     uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	CollectedAtUnixMs int64                  `protobuf:"varint,2,opt,name=collected_at_unix_ms,json=collectedAtUnixMs,proto3" json:"collected_at_unix_ms,omitempty"`
	Domains           []*CareFactDomain      `protobuf:"bytes,3,rep,name=domains,proto3" json:"domains,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CareFactsSnapshot) Reset() {
	*x = CareFactsSnapshot{}
	mi := &file_proto_care_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CareFactsSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CareFactsSnapshot) ProtoMessage() {}

func (x *CareFactsSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_care_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CareFactsSnapshot.ProtoReflect.Descriptor instead.
func (*CareFactsSnapshot) Descriptor() ([]byte, []int) {
	return file_proto_care_proto_rawDescGZIP(), []int{3}
}

func (x *CareFactsSnapshot) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *CareFactsSnapshot) GetCollectedAtUnixMs() int64 {
	if x != nil {
		return x.CollectedAtUnixMs
	}
	return 0
}

func (x *CareFactsSnapshot) GetDomains() []*CareFactDomain {
	if x != nil {
		return x.Domains
	}
	return nil
}

type CareStorageSource struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	SourceCode             string                 `protobuf:"bytes,1,opt,name=source_code,json=sourceCode,proto3" json:"source_code,omitempty"`
	SourceVersion          uint32                 `protobuf:"varint,2,opt,name=source_version,json=sourceVersion,proto3" json:"source_version,omitempty"`
	Class                  string                 `protobuf:"bytes,3,opt,name=class,proto3" json:"class,omitempty"`
	LogicalBytes           uint64                 `protobuf:"varint,4,opt,name=logical_bytes,json=logicalBytes,proto3" json:"logical_bytes,omitempty"`
	ReportedAllocatedBytes *uint64                `protobuf:"varint,5,opt,name=reported_allocated_bytes,json=reportedAllocatedBytes,proto3,oneof" json:"reported_allocated_bytes,omitempty"`
	EstimatedReclaimBytes  *uint64                `protobuf:"varint,6,opt,name=estimated_reclaim_bytes,json=estimatedReclaimBytes,proto3,oneof" json:"estimated_reclaim_bytes,omitempty"`
	EstimationQuality      string                 `protobuf:"bytes,7,opt,name=estimation_quality,json=estimationQuality,proto3" json:"estimation_quality,omitempty"`
	Coverage               string                 `protobuf:"bytes,8,opt,name=coverage,proto3" json:"coverage,omitempty"`
	ReasonCode             string                 `protobuf:"bytes,9,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	Eligibility            string                 `protobuf:"bytes,10,opt,name=eligibility,proto3" json:"eligibility,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CareStorageSource) Reset() {
	*x = CareStorageSource{}
	mi := &file_proto_care_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CareStorageSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CareStorageSource) ProtoMessage() {}

func (x *CareStorageSource) ProtoReflect() protoreflect.Message {
	mi := &file_proto_care_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CareStorageSource.ProtoReflect.Descriptor instead.
func (*CareStorageSource) Descriptor() ([]byte, []int) {
	return file_proto_care_proto_rawDescGZIP(), []int{4}
}

func (x *CareStorageSource) GetSourceCode() string {
	if x != nil {
		return x.SourceCode
	}
	return ""
}

func (x *CareStorageSource) GetSourceVersion() uint32 {
	if x != nil {
		return x.SourceVersion
	}
	return 0
}

func (x *CareStorageSource) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *CareStorageSource) GetLogicalBytes() uint64 {
	if x != nil {
		return x.LogicalBytes
	}
	return 0
}

func (x *CareStorageSource) GetReportedAllocatedBytes() uint64 {
	if x != nil && x.ReportedAllocatedBytes != nil {
		return *x.ReportedAllocatedBytes
	}
	return 0
}

func (x *CareStorageSource) GetEstimatedReclaimBytes() uint64 {
	if x != nil && x.EstimatedReclaimBytes != nil {
		return *x.EstimatedReclaimBytes
	}
	return 0
}

func (x *CareStorageSource) GetEstimationQuality() string {
	if x != nil {
		return x.EstimationQuality
	}
	return ""
}

func (x *CareStorageSource) GetCoverage() string {
	if x != nil {
		return x.Coverage
	}
	return ""
}

func (x *CareStorageSource) GetReasonCode() string {
	if x != nil {
		return x.ReasonCode
	}
	return ""
}

func (x *CareStorageSource) GetEligibility() string {
	if x != nil {
		return x.Eligibility
	}
	return ""
}

type CareStorageSnapshot struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion    uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	CapturedAtUnixMs int64                  `protobuf:"varint,2,opt,name=captured_at_unix_ms,json=capturedAtUnixMs,proto3" json:"captured_at_unix_ms,omitempty"`
	FinishedAtUnixMs int64                  `protobuf:"varint,3,opt,name=finished_at_unix_ms,json=finishedAtUnixMs,proto3" json:"finished_at_unix_ms,omitempty"`
	Coverage         string                 `protobuf:"bytes,4,opt,name=coverage,proto3" json:"coverage,omitempty"`
	ReasonCode       string                 `protobuf:"bytes,5,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	Sources          []*CareStorageSource   `protobuf:"bytes,6,rep,name=sources,proto3" json:"sources,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CareStorageSnapshot) Reset() {
	*x = CareStorageSnapshot{}
	mi := &file_proto_care_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CareStorageSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CareStorageSnapshot) ProtoMessage() {}

func (x *CareStorageSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_care_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CareStorageSnapshot.ProtoReflect.Descriptor instead.
func (*CareStorageSnapshot) Descriptor() ([]byte, []int) {
	return file_proto_care_proto_rawDescGZIP(), []int{5}
}

func (x *CareStorageSnapshot) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *CareStorageSnapshot) GetCapturedAtUnixMs() int64 {
	if x != nil {
		return x.CapturedAtUnixMs
	}
	return 0
}

func (x *CareStorageSnapshot) GetFinishedAtUnixMs() int64 {
	if x != nil {
		return x.FinishedAtUnixMs
	}
	return 0
}

func (x *CareStorageSnapshot) GetCoverage() string {
	if x != nil {
		return x.Coverage
	}
	return ""
}

func (x *CareStorageSnapshot) GetReasonCode() string {
	if x != nil {
		return x.ReasonCode
	}
	return ""
}

func (x *CareStorageSnapshot) GetSources() []*CareStorageSource {
	if x != nil {
		return x.Sources
	}
	return nil
}

type CareTerminalScan struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PolicyVersion     string                 `protobuf:"bytes,1,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	CapabilityVersion string                 `protobuf:"bytes,2,opt,name=capability_version,json=capabilityVersion,proto3" json:"capability_version,omitempty"`
	TerminalState     string                 `protobuf:"bytes,3,opt,name=terminal_state,json=terminalState,proto3" json:"terminal_state,omitempty"`
	Coverage          string                 `protobuf:"bytes,4,opt,name=coverage,proto3" json:"coverage,omitempty"`
	ReasonCode        string                 `protobuf:"bytes,5,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	FinishedAtUnixMs  int64                  `protobuf:"varint,6,opt,name=finished_at_unix_ms,json=finishedAtUnixMs,proto3" json:"finished_at_unix_ms,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CareTerminalScan) Reset() {
	*x = CareTerminalScan{}
	mi := &file_proto_care_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CareTerminalScan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CareTerminalScan) ProtoMessage() {}

func (x *CareTerminalScan) ProtoReflect() protoreflect.Message {
	mi := &file_proto_care_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CareTerminalScan.ProtoReflect.Descriptor instead.
func (*CareTerminalScan) Descriptor() ([]byte, []int) {
	return file_proto_care_proto_rawDescGZIP(), []int{6}
}

func (x *CareTerminalScan) GetPolicyVersion() string {
	if x != nil {
		return x.PolicyVersion
	}
	return ""
}

func (x *CareTerminalScan) GetCapabilityVersion() string {
	if x != nil {
		return x.CapabilityVersion
	}
	return ""
}

func (x *CareTerminalScan) GetTerminalState() string {
	if x != nil {
		return x.TerminalState
	}
	return ""
}

func (x *CareTerminalScan) GetCoverage() string {
	if x != nil {
		return x.Coverage
	}
	return ""
}

func (x *CareTerminalScan) GetReasonCode() string {
	if x != nil {
		return x.ReasonCode
	}
	return ""
}

func (x *CareTerminalScan) GetFinishedAtUnixMs() int64 {
	if x != nil {
		return x.FinishedAtUnixMs
	}
	return 0
}

type CareFinding struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ProjectionId       string                 `protobuf:"bytes,1,opt,name=projection_id,json=projectionId,proto3" json:"projection_id,omitempty"`
	RuleCode           string                 `protobuf:"bytes,2,opt,name=rule_code,json=ruleCode,proto3" json:"rule_code,omitempty"`
	RuleVersion        string                 `protobuf:"bytes,3,opt,name=rule_version,json=ruleVersion,proto3" json:"rule_version,omitempty"`
	Domain             string                 `protobuf:"bytes,4,opt,name=domain,proto3" json:"domain,omitempty"`
	PresentationCode   string                 `protobuf:"bytes,5,opt,name=presentation_code,json=presentationCode,proto3" json:"presentation_code,omitempty"`
	NextStepCode       string                 `protobuf:"bytes,6,opt,name=next_step_code,json=nextStepCode,proto3" json:"next_step_code,omitempty"`
	Severity           string                 `protobuf:"bytes,7,opt,name=severity,proto3" json:"severity,omitempty"`
	Coverage           string                 `protobuf:"bytes,8,opt,name=coverage,proto3" json:"coverage,omitempty"`
	ReasonCode         string                 `protobuf:"bytes,9,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	Revision           uint64                 `protobuf:"varint,10,opt,name=revision,proto3" json:"revision,omitempty"`
	LastTransition     string                 `protobuf:"bytes,11,opt,name=last_transition,json=lastTransition,proto3" json:"last_transition,omitempty"`
	TransitionAtUnixMs int64                  `protobuf:"varint,12,opt,name=transition_at_unix_ms,json=transitionAtUnixMs,proto3" json:"transition_at_unix_ms,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CareFinding) Reset() {
	*x = CareFinding{}
	mi := &file_proto_care_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CareFinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CareFinding) ProtoMessage() {}

func (x *CareFinding) ProtoReflect() protoreflect.Message {
	mi := &file_proto_care_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CareFinding.ProtoReflect.Descriptor instead.
func (*CareFinding) Descriptor() ([]byte, []int) {
	return file_proto_care_proto_rawDescGZIP(), []int{7}
}

func (x *CareFinding) GetProjectionId() string {
	if x != nil {
		return x.ProjectionId
	}
	return ""
}

func (x *CareFinding) GetRuleCode() string {
	if x != nil {
		return x.RuleCode
	}
	return ""
}

func (x *CareFinding) GetRuleVersion() string {
	if x != nil {
		return x.RuleVersion
	}
	return ""
}

func (x *CareFinding) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *CareFinding) GetPresentationCode() string {
	if x != nil {
		return x.PresentationCode
	}
	return ""
}

func (x *CareFinding) GetNextStepCode() string {
	if x != nil {
		return x.NextStepCode
	}
	return ""
}

func (x *CareFinding) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *CareFinding) GetCoverage() string {
	if x != nil {
		return x.Coverage
	}
	return ""
}

func (x *CareFinding) GetReasonCode() string {
	if x != nil {
		return x.ReasonCode
	}
	return ""
}

func (x *CareFinding) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *CareFinding) GetLastTransition() string {
	if x != nil {
		return x.LastTransition
	}
	return ""
}

func (x *CareFinding) GetTransitionAtUnixMs() int64 {
	if x != nil {
		return x.TransitionAtUnixMs
	}
	return 0
}

type CareSnapshot struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion          uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	SourceInstanceId       string                 `protobuf:"bytes,2,opt,name=source_instance_id,json=sourceInstanceId,proto3" json:"source_instance_id,omitempty"`
	SourceGeneration       uint64                 `protobuf:"varint,3,opt,name=source_generation,json=sourceGeneration,proto3" json:"source_generation,omitempty"`
	LatestScan             *CareTerminalScan      `protobuf:"bytes,4,opt,name=latest_scan,json=latestScan,proto3" json:"latest_scan,omitempty"`
	Findings               []*CareFinding         `protobuf:"bytes,5,rep,name=findings,proto3" json:"findings,omitempty"`
	LatestFacts            *CareFactsSnapshot     `protobuf:"bytes,6,opt,name=latest_facts,json=latestFacts,proto3" json:"latest_facts,omitempty"`
	LatestStorageInventory *CareStorageSnapshot   `protobuf:"bytes,7,opt,name=latest_storage_inventory,json=latestStorageInventory,proto3" json:"latest_storage_inventory,omitempty"`
	Capabilities           *CareCapabilities      `protobuf:"bytes,8,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CareSnapshot) Reset() {
	*x = CareSnapshot{}
	mi := &file_proto_care_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CareSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CareSnapshot) ProtoMessage() {}

func (x *CareSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_care_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CareSnapshot.ProtoReflect.Descriptor instead.
func (*CareSnapshot) Descriptor() ([]byte, []int) {
	return file_proto_care_proto_rawDescGZIP(), []int{8}
}

func (x *CareSnapshot) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *CareSnapshot) GetSourceInstanceId() string {
	if x != nil {
		return x.SourceInstanceId
	}
	return ""
}

func (x *CareSnapshot) GetSourceGeneration() uint64 {
	if x != nil {
		return x.SourceGeneration
	}
	return 0
}

func (x *CareSnapshot) GetLatestScan() *CareTerminalScan {
	if x != nil {
		return x.LatestScan
	}
	return nil
}

func (x *CareSnapshot) GetFindings() []*CareFinding {
	if x != nil {
		return x.Findings
	}
	return nil
}

func (x *CareSnapshot) GetLatestFacts() *CareFactsSnapshot {
	if x != nil {
		return x.LatestFacts
	}
	return nil
}

func (x *CareSnapshot) GetLatestStorageInventory() *CareStorageSnapshot {
	if x != nil {
		return x.LatestStorageInventory
	}
	return nil
}

func (x *CareSnapshot) GetCapabilities() *CareCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

// CareDiagnostic mirrors the local diagnostic privacy allowlist: no command
// lines, paths, users, environment, registry values, or startup configuration
// contents. Raw process PID and process name ARE present (see
// CareProcessAttribution) — this is a deliberate, disclosed part of the
// contract; see this artifact's README and the care_diagnose tool description.
type CareDiagnostic struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion           uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	ScanRunId               string                 `protobuf:"bytes,2,opt,name=scan_run_id,json=scanRunId,proto3" json:"scan_run_id,omitempty"`
	CaptureStartedAtUnixMs  int64                  `protobuf:"varint,3,opt,name=capture_started_at_unix_ms,json=captureStartedAtUnixMs,proto3" json:"capture_started_at_unix_ms,omitempty"`
	CaptureFinishedAtUnixMs int64                  `protobuf:"varint,4,opt,name=capture_finished_at_unix_ms,json=captureFinishedAtUnixMs,proto3" json:"capture_finished_at_unix_ms,omitempty"`
	TriggerCode             string                 `protobuf:"bytes,5,opt,name=trigger_code,json=triggerCode,proto3" json:"trigger_code,omitempty"`
	Coverage                string                 `protobuf:"bytes,6,opt,name=coverage,proto3" json:"coverage,omitempty"`
	ReasonCode              string                 `protobuf:"bytes,7,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	Processes               *CareProcessDiagnostic `protobuf:"bytes,8,opt,name=processes,proto3" json:"processes,omitempty"`
	Startup                 *CareStartupDiagnostic `protobuf:"bytes,9,opt,name=startup,proto3" json:"startup,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *CareDiagnostic) Reset() {
	*x = CareDiagnostic{}
	mi := &file_proto_care_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CareDiagnostic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CareDiagnostic) ProtoMessage() {}

func (x *CareDiagnostic) ProtoReflect() protoreflect.Message {
	mi := &file_proto_care_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CareDiagnostic.ProtoReflect.Descriptor instead.
func (*CareDiagnostic) Descriptor() ([]byte, []int) {
	return file_proto_care_proto_rawDescGZIP(), []int{9}
}

func (x *CareDiagnostic) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *CareDiagnostic) GetScanRunId() string {
	if x != nil {
		return x.ScanRunId
	}
	return ""
}

func (x *CareDiagnostic) GetCaptureStartedAtUnixMs() int64 {
	if x != nil {
		return x.CaptureStartedAtUnixMs
	}
	return 0
}

func (x *CareDiagnostic) GetCaptureFinishedAtUnixMs() int64 {
	if x != nil {
		return x.CaptureFinishedAtUnixMs
	}
	return 0
}

func (x *CareDiagnostic) GetTriggerCode() string {
	if x != nil {
		return x.TriggerCode
	}
	return ""
}

func (x *CareDiagnostic) GetCoverage() string {
	if x != nil {
		return x.Coverage
	}
	return ""
}

func (x *CareDiagnostic) GetReasonCode() string {
	if x != nil {
		return x.ReasonCode
	}
	return ""
}

func (x *CareDiagnostic) GetProcesses() *CareProcessDiagnostic {
	if x != nil {
		return x.Processes
	}
	return nil
}

func (x *CareDiagnostic) GetStartup() *CareStartupDiagnostic {
	if x != nil {
		return x.Startup
	}
	return nil
}

type CareProcessDiagnostic struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Coverage      string                    `protobuf:"bytes,1,opt,name=coverage,proto3" json:"coverage,omitempty"`
	ReasonCode    string                    `protobuf:"bytes,2,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	ExaminedCount uint32                    `protobuf:"varint,3,opt,name=examined_count,json=examinedCount,proto3" json:"examined_count,omitempty"`
	RetainedCount uint32                    `protobuf:"varint,4,opt,name=retained_count,json=retainedCount,proto3" json:"retained_count,omitempty"`
	Truncated     bool                      `protobuf:"varint,5,opt,name=truncated,proto3" json:"truncated,omitempty"`
	Entries       []*CareProcessAttribution `protobuf:"bytes,6,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CareProcessDiagnostic) Reset() {
	*x = CareProcessDiagnostic{}
	mi := &file_proto_care_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CareProcessDiagnostic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CareProcessDiagnostic) ProtoMessage() {}

func (x *CareProcessDiagnostic) ProtoReflect() protoreflect.Message {
	mi := &file_proto_care_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CareProcessDiagnostic.ProtoReflect.Descriptor instead.
func (*CareProcessDiagnostic) Descriptor() ([]byte, []int) {
	return file_proto_care_proto_rawDescGZIP(), []int{10}
}

func (x *CareProcessDiagnostic) GetCoverage() string {
	if x != nil {
		return x.Coverage
	}
	return ""
}

func (x *CareProcessDiagnostic) GetReasonCode() string {
	if x != nil {
		return x.ReasonCode
	}
	return ""
}

func (x *CareProcessDiagnostic) GetExaminedCount() uint32 {
	if x != nil {
		return x.ExaminedCount
	}
	return 0
}

func (x *CareProcessDiagnostic) GetRetainedCount() uint32 {
	if x != nil {
		return x.RetainedCount
	}
	return 0
}

func (x *CareProcessDiagnostic) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

func (x *CareProcessDiagnostic) GetEntries() []*CareProcessAttribution {
	if x != nil {
		return x.Entries
	}
	return nil
}

type CareProcessAttribution struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Pid             int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	StartedAtUnixMs int64                  `protobuf:"varint,2,opt,name=started_at_unix_ms,json=startedAtUnixMs,proto3" json:"started_at_unix_ms,omitempty"`
	Name            string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	CpuMilliPercent int64                  `protobuf:"varint,4,opt,name=cpu_milli_percent,json=cpuMilliPercent,proto3" json:"cpu_milli_percent,omitempty"`
	RssBytes        uint64                 `protobuf:"varint,5,opt,name=rss_bytes,json=rssBytes,proto3" json:"rss_bytes,omitempty"`
	CpuLeader       bool                   `protobuf:"varint,6,opt,name=cpu_leader,json=cpuLeader,proto3" json:"cpu_leader,omitempty"`
	RssLeader       bool                   `protobuf:"varint,7,opt,name=rss_leader,json=rssLeader,proto3" json:"rss_leader,omitempty"`
	CandidateId     string                 `protobuf:"bytes,8,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CareProcessAttribution) Reset() {
	*x = CareProcessAttribution{}
	mi := &file_proto_care_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CareProcessAttribution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CareProcessAttribution) ProtoMessage() {}

func (x *CareProcessAttribution) ProtoReflect() protoreflect.Message {
	mi := &file_proto_care_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CareProcessAttribution.ProtoReflect.Descriptor instead.
func (*CareProcessAttribution) Descriptor() ([]byte, []int) {
	return file_proto_care_proto_rawDescGZIP(), []int{11}
}

func (x *CareProcessAttribution) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *CareProcessAttribution) GetStartedAtUnixMs() int64 {
	if x != nil {
		return x.StartedAtUnixMs
	}
	return 0
}

func (x *CareProcessAttribution) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CareProcessAttribution) GetCpuMilliPercent() int64 {
	if x != nil {
		return x.CpuMilliPercent
	}
	return 0
}

func (x *CareProcessAttribution) GetRssBytes() uint64 {
	if x != nil {
		return x.RssBytes
	}
	return 0
}

func (x *CareProcessAttribution) GetCpuLeader() bool {
	if x != nil {
		return x.CpuLeader
	}
	return false
}

func (x *CareProcessAttribution) GetRssLeader() bool {
	if x != nil {
		return x.RssLeader
	}
	return false
}

func (x *CareProcessAttribution) GetCandidateId() string {
	if x != nil {
		return x.CandidateId
	}
	return ""
}

type CareStartupDiagnostic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coverage      string                 `protobuf:"bytes,1,opt,name=coverage,proto3" json:"coverage,omitempty"`
	ReasonCode    string                 `protobuf:"bytes,2,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	ExaminedCount uint32                 `protobuf:"varint,3,opt,name=examined_count,json=examinedCount,proto3" json:"examined_count,omitempty"`
	RetainedCount uint32                 `protobuf:"varint,4,opt,name=retained_count,json=retainedCount,proto3" json:"retained_count,omitempty"`
	Truncated     bool                   `protobuf:"varint,5,opt,name=truncated,proto3" json:"truncated,omitempty"`
	Sources       []*CareStartupSource   `protobuf:"bytes,6,rep,name=sources,proto3" json:"sources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CareStartupDiagnostic) Reset() {
	*x = CareStartupDiagnostic{}
	mi := &file_proto_care_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CareStartupDiagnostic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CareStartupDiagnostic) ProtoMessage() {}

func (x *CareStartupDiagnostic) ProtoReflect() protoreflect.Message {
	mi := &file_proto_care_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CareStartupDiagnostic.ProtoReflect.Descriptor instead.
func (*CareStartupDiagnostic) Descriptor() ([]byte, []int) {
	return file_proto_care_proto_rawDescGZIP(), []int{12}
}

func (x *CareStartupDiagnostic) GetCoverage() string {
	if x != nil {
		return x.Coverage
	}
	return ""
}

func (x *CareStartupDiagnostic) GetReasonCode() string {
	if x != nil {
		return x.ReasonCode
	}
	return ""
}

func (x *CareStartupDiagnostic) GetExaminedCount() uint32 {
	if x != nil {
		return x.ExaminedCount
	}
	return 0
}

func (x *CareStartupDiagnostic) GetRetainedCount() uint32 {
	if x != nil {
		return x.RetainedCount
	}
	return 0
}

func (x *CareStartupDiagnostic) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

func (x *CareStartupDiagnostic) GetSources() []*CareStartupSource {
	if x != nil {
		return x.Sources
	}
	return nil
}

type CareStartupSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceCode    string                 `protobuf:"bytes,1,opt,name=source_code,json=sourceCode,proto3" json:"source_code,omitempty"`
	Scope         string                 `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	Coverage      string                 `protobuf:"bytes,3,opt,name=coverage,proto3" json:"coverage,omitempty"`
	ReasonCode    string                 `protobuf:"bytes,4,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	ExaminedCount uint32                 `protobuf:"varint,5,opt,name=examined_count,json=examinedCount,proto3" json:"examined_count,omitempty"`
	RetainedCount uint32                 `protobuf:"varint,6,opt,name=retained_count,json=retainedCount,proto3" json:"retained_count,omitempty"`
	Truncated     bool                   `protobuf:"varint,7,opt,name=truncated,proto3" json:"truncated,omitempty"`
	Entries       []*CareStartupEntry    `protobuf:"bytes,8,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CareStartupSource) Reset() {
	*x = CareStartupSource{}
	mi := &file_proto_care_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CareStartupSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CareStartupSource) ProtoMessage() {}

func (x *CareStartupSource) ProtoReflect() protoreflect.Message {
	mi := &file_proto_care_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CareStartupSource.ProtoReflect.Descriptor instead.
func (*CareStartupSource) Descriptor() ([]byte, []int) {
	return file_proto_care_proto_rawDescGZIP(), []int{13}
}

func (x *CareStartupSource) GetSourceCode() string {
	if x != nil {
		return x.SourceCode
	}
	return ""
}

func (x *CareStartupSource) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *CareStartupSource) GetCoverage() string {
	if x != nil {
		return x.Coverage
	}
	return ""
}

func (x *CareStartupSource) GetReasonCode() string {
	if x != nil {
		return x.ReasonCode
	}
	return ""
}

func (x *CareStartupSource) GetExaminedCount() uint32 {
	if x != nil {
		return x.ExaminedCount
	}
	return 0
}

func (x *CareStartupSource) GetRetainedCount() uint32 {
	if x != nil {
		return x.RetainedCount
	}
	return 0
}

func (x *CareStartupSource) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

func (x *CareStartupSource) GetEntries() []*CareStartupEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type CareStartupEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	SourceCode    string                 `protobuf:"bytes,3,opt,name=source_code,json=sourceCode,proto3" json:"source_code,omitempty"`
	Scope         string                 `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`
	Kind          string                 `protobuf:"bytes,5,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CareStartupEntry) Reset() {
	*x = CareStartupEntry{}
	mi := &file_proto_care_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CareStartupEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CareStartupEntry) ProtoMessage() {}

func (x *CareStartupEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_care_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CareStartupEntry.ProtoReflect.Descriptor instead.
func (*CareStartupEntry) Descriptor() ([]byte, []int) {
	return file_proto_care_proto_rawDescGZIP(), []int{14}
}

func (x *CareStartupEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CareStartupEntry) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *CareStartupEntry) GetSourceCode() string {
	if x != nil {
		return x.SourceCode
	}
	return ""
}

func (x *CareStartupEntry) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *CareStartupEntry) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type GetMachineCareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Machine       string                 `protobuf:"bytes,1,opt,name=machine,proto3" json:"machine,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMachineCareRequest) Reset() {
	*x = GetMachineCareRequest{}
	mi := &file_proto_care_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMachineCareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMachineCareRequest) ProtoMessage() {}

func (x *GetMachineCareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_care_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMachineCareRequest.ProtoReflect.Descriptor instead.
func (*GetMachineCareRequest) Descriptor() ([]byte, []int) {
	return file_proto_care_proto_rawDescGZIP(), []int{15}
}

func (x *GetMachineCareRequest) GetMachine() string {
	if x != nil {
		return x.Machine
	}
	return ""
}

type GetMachineCareResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MachineId     string                 `protobuf:"bytes,1,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	Reported      bool                   `protobuf:"varint,2,opt,name=reported,proto3" json:"reported,omitempty"`
	Snapshot      *CareSnapshot          `protobuf:"bytes,3,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMachineCareResponse) Reset() {
	*x = GetMachineCareResponse{}
	mi := &file_proto_care_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMachineCareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMachineCareResponse) ProtoMessage() {}

func (x *GetMachineCareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_care_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMachineCareResponse.ProtoReflect.Descriptor instead.
func (*GetMachineCareResponse) Descriptor() ([]byte, []int) {
	return file_proto_care_proto_rawDescGZIP(), []int{16}
}

func (x *GetMachineCareResponse) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *GetMachineCareResponse) GetReported() bool {
	if x != nil {
		return x.Reported
	}
	return false
}

func (x *GetMachineCareResponse) GetSnapshot() *CareSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type RunMachineCareDiagnosticRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Machine       string                 `protobuf:"bytes,1,opt,name=machine,proto3" json:"machine,omitempty"`
	MachinePin    string                 `protobuf:"bytes,2,opt,name=machine_pin,json=machinePin,proto3" json:"machine_pin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunMachineCareDiagnosticRequest) Reset() {
	*x = RunMachineCareDiagnosticRequest{}
	mi := &file_proto_care_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunMachineCareDiagnosticRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunMachineCareDiagnosticRequest) ProtoMessage() {}

func (x *RunMachineCareDiagnosticRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_care_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunMachineCareDiagnosticRequest.ProtoReflect.Descriptor instead.
func (*RunMachineCareDiagnosticRequest) Descriptor() ([]byte, []int) {
	return file_proto_care_proto_rawDescGZIP(), []int{17}
}

func (x *RunMachineCareDiagnosticRequest) GetMachine() string {
	if x != nil {
		return x.Machine
	}
	return ""
}

func (x *RunMachineCareDiagnosticRequest) GetMachinePin() string {
	if x != nil {
		return x.MachinePin
	}
	return ""
}

type RunMachineCareDiagnosticResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MachineId     string                 `protobuf:"bytes,1,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	Diagnostic    *CareDiagnostic        `protobuf:"bytes,2,opt,name=diagnostic,proto3" json:"diagnostic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunMachineCareDiagnosticResponse) Reset() {
	*x = RunMachineCareDiagnosticResponse{}
	mi := &file_proto_care_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunMachineCareDiagnosticResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunMachineCareDiagnosticResponse) ProtoMessage() {}

func (x *RunMachineCareDiagnosticResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_care_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunMachineCareDiagnosticResponse.ProtoReflect.Descriptor instead.
func (*RunMachineCareDiagnosticResponse) Descriptor() ([]byte, []int) {
	return file_proto_care_proto_rawDescGZIP(), []int{18}
}

func (x *RunMachineCareDiagnosticResponse) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *RunMachineCareDiagnosticResponse) GetDiagnostic() *CareDiagnostic {
	if x != nil {
		return x.Diagnostic
	}
	return nil
}

type SessionInfo struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	SessionId           string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	FleetId             string                 `protobuf:"bytes,2,opt,name=fleet_id,json=fleetId,proto3" json:"fleet_id,omitempty"`
	MachineId           string                 `protobuf:"bytes,3,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	DisplayName         string                 `protobuf:"bytes,6,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Status              SessionStatus          `protobuf:"varint,7,opt,name=status,proto3,enum=cmdop.care.v1.SessionStatus" json:"status,omitempty"`
	Os                  string                 `protobuf:"bytes,8,opt,name=os,proto3" json:"os,omitempty"`
	AgentVersion        string                 `protobuf:"bytes,9,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	HasShell            bool                   `protobuf:"varint,10,opt,name=has_shell,json=hasShell,proto3" json:"has_shell,omitempty"`
	Shell               string                 `protobuf:"bytes,11,opt,name=shell,proto3" json:"shell,omitempty"`
	WorkingDirectory    string                 `protobuf:"bytes,12,opt,name=working_directory,json=workingDirectory,proto3" json:"working_directory,omitempty"`
	HeartbeatAgeSeconds int64                  `protobuf:"varint,13,opt,name=heartbeat_age_seconds,json=heartbeatAgeSeconds,proto3" json:"heartbeat_age_seconds,omitempty"`
	ConnectedAt         *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=connected_at,json=connectedAt,proto3" json:"connected_at,omitempty"`
	LastHeartbeatAt     *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=last_heartbeat_at,json=lastHeartbeatAt,proto3" json:"last_heartbeat_at,omitempty"`
	CreatedAt           *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	PublicUrl           string                 `protobuf:"bytes,17,opt,name=public_url,json=publicUrl,proto3" json:"public_url,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SessionInfo) Reset() {
	*x = SessionInfo{}
	mi := &file_proto_care_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionInfo) ProtoMessage() {}

func (x *SessionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_care_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionInfo.ProtoReflect.Descriptor instead.
func (*SessionInfo) Descriptor() ([]byte, []int) {
	return file_proto_care_proto_rawDescGZIP(), []int{19}
}

func (x *SessionInfo) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionInfo) GetFleetId() string {
	if x != nil {
		return x.FleetId
	}
	return ""
}

func (x *SessionInfo) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *SessionInfo) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *SessionInfo) GetStatus() SessionStatus {
	if x != nil {
		return x.Status
	}
	return SessionStatus_SESSION_STATUS_UNSPECIFIED
}

func (x *SessionInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *SessionInfo) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *SessionInfo) GetHasShell() bool {
	if x != nil {
		return x.HasShell
	}
	return false
}

func (x *SessionInfo) GetShell() string {
	if x != nil {
		return x.Shell
	}
	return ""
}

func (x *SessionInfo) GetWorkingDirectory() string {
	if x != nil {
		return x.WorkingDirectory
	}
	return ""
}

func (x *SessionInfo) GetHeartbeatAgeSeconds() int64 {
	if x != nil {
		return x.HeartbeatAgeSeconds
	}
	return 0
}

func (x *SessionInfo) GetConnectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ConnectedAt
	}
	return nil
}

func (x *SessionInfo) GetLastHeartbeatAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastHeartbeatAt
	}
	return nil
}

func (x *SessionInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SessionInfo) GetPublicUrl() string {
	if x != nil {
		return x.PublicUrl
	}
	return ""
}

type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FleetId       string                 `protobuf:"bytes,1,opt,name=fleet_id,json=fleetId,proto3" json:"fleet_id,omitempty"`
	MachineId     string                 `protobuf:"bytes,2,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Status        SessionStatus          `protobuf:"varint,4,opt,name=status,proto3,enum=cmdop.care.v1.SessionStatus" json:"status,omitempty"`
	PageSize      int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,6,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_proto_care_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_care_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_care_proto_rawDescGZIP(), []int{20}
}

func (x *ListSessionsRequest) GetFleetId() string {
	if x != nil {
		return x.FleetId
	}
	return ""
}

func (x *ListSessionsRequest) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *ListSessionsRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ListSessionsRequest) GetStatus() SessionStatus {
	if x != nil {
		return x.Status
	}
	return SessionStatus_SESSION_STATUS_UNSPECIFIED
}

func (x *ListSessionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListSessionsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*SessionInfo         `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_proto_care_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_care_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_care_proto_rawDescGZIP(), []int{21}
}

func (x *ListSessionsResponse) GetSessions() []*SessionInfo {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *ListSessionsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_proto_care_proto protoreflect.FileDescriptor

const file_proto_care_proto_rawDesc = "" +
	"\n" +
	"\x10proto/care.proto\x12\rcmdop.care.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"R\n" +
	"\x10CareCapabilities\x12>\n" +
	"\x1bremote_diagnostic_supported\x18\x01 \x01(\bR\x19remoteDiagnosticSupported\"\xb4\x01\n" +
	"\bCareFact\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value\x12\x12\n" +
	"\x04unit\x18\x03 \x01(\tR\x04unit\x12\x1a\n" +
	"\bcoverage\x18\x04 \x01(\tR\bcoverage\x12\x1f\n" +
	"\vreason_code\x18\x05 \x01(\tR\n" +
	"reasonCode\x12-\n" +
	"\x13captured_at_unix_ms\x18\x06 \x01(\x03R\x10capturedAtUnixMs\"\xbf\x01\n" +
	"\x0eCareFactDomain\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x1a\n" +
	"\bcoverage\x18\x02 \x01(\tR\bcoverage\x12\x1f\n" +
	"\vreason_code\x18\x03 \x01(\tR\n" +
	"reasonCode\x12-\n" +
	"\x13captured_at_unix_ms\x18\x04 \x01(\x03R\x10capturedAtUnixMs\x12-\n" +
	"\x05facts\x18\x05 \x03(\v2\x17.cmdop.care.v1.CareFactR\x05facts\"\xa4\x01\n" +
	"\x11CareFactsSnapshot\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12/\n" +
	"\x14collected_at_unix_ms\x18\x02 \x01(\x03R\x11collectedAtUnixMs\x127\n" +
	"\adomains\x18\x03 \x03(\v2\x1d.cmdop.care.v1.CareFactDomainR\adomains\"\xd9\x03\n" +
	"\x11CareStorageSource\x12\x1f\n" +
	"\vsource_code\x18\x01 \x01(\tR\n" +
	"sourceCode\x12%\n" +
	"\x0esource_version\x18\x02 \x01(\rR\rsourceVersion\x12\x14\n" +
	"\x05class\x18\x03 \x01(\tR\x05class\x12#\n" +
	"\rlogical_bytes\x18\x04 \x01(\x04R\flogicalBytes\x12=\n" +
	"\x18reported_allocated_bytes\x18\x05 \x01(\x04H\x00R\x16reportedAllocatedBytes\x88\x01\x01\x12;\n" +
	"\x17estimated_reclaim_bytes\x18\x06 \x01(\x04H\x01R\x15estimatedReclaimBytes\x88\x01\x01\x12-\n" +
	"\x12estimation_quality\x18\a \x01(\tR\x11estimationQuality\x12\x1a\n" +
	"\bcoverage\x18\b \x01(\tR\bcoverage\x12\x1f\n" +
	"\vreason_code\x18\t \x01(\tR\n" +
	"reasonCode\x12 \n" +
	"\veligibility\x18\n" +
	" \x01(\tR\veligibilityB\x1b\n" +
	"\x19_reported_allocated_bytesB\x1a\n" +
	"\x18_estimated_reclaim_bytes\"\x93\x02\n" +
	"\x13CareStorageSnapshot\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12-\n" +
	"\x13captured_at_unix_ms\x18\x02 \x01(\x03R\x10capturedAtUnixMs\x12-\n" +
	"\x13finished_at_unix_ms\x18\x03 \x01(\x03R\x10finishedAtUnixMs\x12\x1a\n" +
	"\bcoverage\x18\x04 \x01(\tR\bcoverage\x12\x1f\n" +
	"\vreason_code\x18\x05 \x01(\tR\n" +
	"reasonCode\x12:\n" +
	"\asources\x18\x06 \x03(\v2 .cmdop.care.v1.CareStorageSourceR\asources\"\xfb\x01\n" +
	"\x10CareTerminalScan\x12%\n" +
	"\x0epolicy_version\x18\x01 \x01(\tR\rpolicyVersion\x12-\n" +
	"\x12capability_version\x18\x02 \x01(\tR\x11capabilityVersion\x12%\n" +
	"\x0eterminal_state\x18\x03 \x01(\tR\rterminalState\x12\x1a\n" +
	"\bcoverage\x18\x04 \x01(\tR\bcoverage\x12\x1f\n" +
	"\vreason_code\x18\x05 \x01(\tR\n" +
	"reasonCode\x12-\n" +
	"\x13finished_at_unix_ms\x18\x06 \x01(\x03R\x10finishedAtUnixMs\"\xae\x03\n" +
	"\vCareFinding\x12#\n" +
	"\rprojection_id\x18\x01 \x01(\tR\fprojectionId\x12\x1b\n" +
	"\trule_code\x18\x02 \x01(\tR\bruleCode\x12!\n" +
	"\frule_version\x18\x03 \x01(\tR\vruleVersion\x12\x16\n" +
	"\x06domain\x18\x04 \x01(\tR\x06domain\x12+\n" +
	"\x11presentation_code\x18\x05 \x01(\tR\x10presentationCode\x12$\n" +
	"\x0enext_step_code\x18\x06 \x01(\tR\fnextStepCode\x12\x1a\n" +
	"\bseverity\x18\a \x01(\tR\bseverity\x12\x1a\n" +
	"\bcoverage\x18\b \x01(\tR\bcoverage\x12\x1f\n" +
	"\vreason_code\x18\t \x01(\tR\n" +
	"reasonCode\x12\x1a\n" +
	"\brevision\x18\n" +
	" \x01(\x04R\brevision\x12'\n" +
	"\x0flast_transition\x18\v \x01(\tR\x0elastTransition\x121\n" +
	"\x15transition_at_unix_ms\x18\f \x01(\x03R\x12transitionAtUnixMs\"\xf2\x03\n" +
	"\fCareSnapshot\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12,\n" +
	"\x12source_instance_id\x18\x02 \x01(\tR\x10sourceInstanceId\x12+\n" +
	"\x11source_generation\x18\x03 \x01(\x04R\x10sourceGeneration\x12@\n" +
	"\vlatest_scan\x18\x04 \x01(\v2\x1f.cmdop.care.v1.CareTerminalScanR\n" +
	"latestScan\x126\n" +
	"\bfindings\x18\x05 \x03(\v2\x1a.cmdop.care.v1.CareFindingR\bfindings\x12C\n" +
	"\flatest_facts\x18\x06 \x01(\v2 .cmdop.care.v1.CareFactsSnapshotR\vlatestFacts\x12\\\n" +
	"\x18latest_storage_inventory\x18\a \x01(\v2\".cmdop.care.v1.CareStorageSnapshotR\x16latestStorageInventory\x12C\n" +
	"\fcapabilities\x18\b \x01(\v2\x1f.cmdop.care.v1.CareCapabilitiesR\fcapabilities\"\xb5\x03\n" +
	"\x0eCareDiagnostic\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12\x1e\n" +
	"\vscan_run_id\x18\x02 \x01(\tR\tscanRunId\x12:\n" +
	"\x1acapture_started_at_unix_ms\x18\x03 \x01(\x03R\x16captureStartedAtUnixMs\x12<\n" +
	"\x1bcapture_finished_at_unix_ms\x18\x04 \x01(\x03R\x17captureFinishedAtUnixMs\x12!\n" +
	"\ftrigger_code\x18\x05 \x01(\tR\vtriggerCode\x12\x1a\n" +
	"\bcoverage\x18\x06 \x01(\tR\bcoverage\x12\x1f\n" +
	"\vreason_code\x18\a \x01(\tR\n" +
	"reasonCode\x12B\n" +
	"\tprocesses\x18\b \x01(\v2$.cmdop.care.v1.CareProcessDiagnosticR\tprocesses\x12>\n" +
	"\astartup\x18\t \x01(\v2$.cmdop.care.v1.CareStartupDiagnosticR\astartup\"\x81\x02\n" +
	"\x15CareProcessDiagnostic\x12\x1a\n" +
	"\bcoverage\x18\x01 \x01(\tR\bcoverage\x12\x1f\n" +
	"\vreason_code\x18\x02 \x01(\tR\n" +
	"reasonCode\x12%\n" +
	"\x0eexamined_count\x18\x03 \x01(\rR\rexaminedCount\x12%\n" +
	"\x0eretained_count\x18\x04 \x01(\rR\rretainedCount\x12\x1c\n" +
	"\ttruncated\x18\x05 \x01(\bR\ttruncated\x12?\n" +
	"\aentries\x18\x06 \x03(\v2%.cmdop.care.v1.CareProcessAttributionR\aentries\"\x95\x02\n" +
	"\x16CareProcessAttribution\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12+\n" +
	"\x12started_at_unix_ms\x18\x02 \x01(\x03R\x0fstartedAtUnixMs\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12*\n" +
	"\x11cpu_milli_percent\x18\x04 \x01(\x03R\x0fcpuMilliPercent\x12\x1b\n" +
	"\trss_bytes\x18\x05 \x01(\x04R\brssBytes\x12\x1d\n" +
	"\n" +
	"cpu_leader\x18\x06 \x01(\bR\tcpuLeader\x12\x1d\n" +
	"\n" +
	"rss_leader\x18\a \x01(\bR\trssLeader\x12!\n" +
	"\fcandidate_id\x18\b \x01(\tR\vcandidateId\"\xfc\x01\n" +
	"\x15CareStartupDiagnostic\x12\x1a\n" +
	"\bcoverage\x18\x01 \x01(\tR\bcoverage\x12\x1f\n" +
	"\vreason_code\x18\x02 \x01(\tR\n" +
	"reasonCode\x12%\n" +
	"\x0eexamined_count\x18\x03 \x01(\rR\rexaminedCount\x12%\n" +
	"\x0eretained_count\x18\x04 \x01(\rR\rretainedCount\x12\x1c\n" +
	"\ttruncated\x18\x05 \x01(\bR\ttruncated\x12:\n" +
	"\asources\x18\x06 \x03(\v2 .cmdop.care.v1.CareStartupSourceR\asources\"\xae\x02\n" +
	"\x11CareStartupSource\x12\x1f\n" +
	"\vsource_code\x18\x01 \x01(\tR\n" +
	"sourceCode\x12\x14\n" +
	"\x05scope\x18\x02 \x01(\tR\x05scope\x12\x1a\n" +
	"\bcoverage\x18\x03 \x01(\tR\bcoverage\x12\x1f\n" +
	"\vreason_code\x18\x04 \x01(\tR\n" +
	"reasonCode\x12%\n" +
	"\x0eexamined_count\x18\x05 \x01(\rR\rexaminedCount\x12%\n" +
	"\x0eretained_count\x18\x06 \x01(\rR\rretainedCount\x12\x1c\n" +
	"\ttruncated\x18\a \x01(\bR\ttruncated\x129\n" +
	"\aentries\x18\b \x03(\v2\x1f.cmdop.care.v1.CareStartupEntryR\aentries\"\x83\x01\n" +
	"\x10CareStartupEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x1f\n" +
	"\vsource_code\x18\x03 \x01(\tR\n" +
	"sourceCode\x12\x14\n" +
	"\x05scope\x18\x04 \x01(\tR\x05scope\x12\x12\n" +
	"\x04kind\x18\x05 \x01(\tR\x04kind\"1\n" +
	"\x15GetMachineCareRequest\x12\x18\n" +
	"\amachine\x18\x01 \x01(\tR\amachine\"\x8c\x01\n" +
	"\x16GetMachineCareResponse\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x01 \x01(\tR\tmachineId\x12\x1a\n" +
	"\breported\x18\x02 \x01(\bR\breported\x127\n" +
	"\bsnapshot\x18\x03 \x01(\v2\x1b.cmdop.care.v1.CareSnapshotR\bsnapshot\"\\\n" +
	"\x1fRunMachineCareDiagnosticRequest\x12\x18\n" +
	"\amachine\x18\x01 \x01(\tR\amachine\x12\x1f\n" +
	"\vmachine_pin\x18\x02 \x01(\tR\n" +
	"machinePin\"\x80\x01\n" +
	" RunMachineCareDiagnosticResponse\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x01 \x01(\tR\tmachineId\x12=\n" +
	"\n" +
	"diagnostic\x18\x02 \x01(\v2\x1d.cmdop.care.v1.CareDiagnosticR\n" +
	"diagnostic\"\x95\x05\n" +
	"\vSessionInfo\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x19\n" +
	"\bfleet_id\x18\x02 \x01(\tR\afleetId\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x03 \x01(\tR\tmachineId\x12!\n" +
	"\fdisplay_name\x18\x06 \x01(\tR\vdisplayName\x124\n" +
	"\x06status\x18\a \x01(\x0e2\x1c.cmdop.care.v1.SessionStatusR\x06status\x12\x0e\n" +
	"\x02os\x18\b \x01(\tR\x02os\x12#\n" +
	"\ragent_version\x18\t \x01(\tR\fagentVersion\x12\x1b\n" +
	"\thas_shell\x18\n" +
	" \x01(\bR\bhasShell\x12\x14\n" +
	"\x05shell\x18\v \x01(\tR\x05shell\x12+\n" +
	"\x11working_directory\x18\f \x01(\tR\x10workingDirectory\x122\n" +
	"\x15heartbeat_age_seconds\x18\r \x01(\x03R\x13heartbeatAgeSeconds\x12=\n" +
	"\fconnected_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\vconnectedAt\x12F\n" +
	"\x11last_heartbeat_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\x0flastHeartbeatAt\x129\n" +
	"\n" +
	"created_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"public_url\x18\x11 \x01(\tR\tpublicUrlJ\x04\b\x04\x10\x05J\x04\b\x05\x10\x06R\x10machine_hostnameR\fmachine_name\"\xe4\x01\n" +
	"\x13ListSessionsRequest\x12\x19\n" +
	"\bfleet_id\x18\x01 \x01(\tR\afleetId\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x02 \x01(\tR\tmachineId\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x124\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1c.cmdop.care.v1.SessionStatusR\x06status\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x06 \x01(\tR\tpageToken\"v\n" +
	"\x14ListSessionsResponse\x126\n" +
	"\bsessions\x18\x01 \x03(\v2\x1a.cmdop.care.v1.SessionInfoR\bsessions\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken*f\n" +
	"\rSessionStatus\x12\x1e\n" +
	"\x1aSESSION_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15SESSION_STATUS_ONLINE\x10\x01\x12\x1a\n" +
	"\x16SESSION_STATUS_OFFLINE\x10\x022\xec\x01\n" +
	"\x0eAiAgentService\x12]\n" +
	"\x0eGetMachineCare\x12$.cmdop.care.v1.GetMachineCareRequest\x1a%.cmdop.care.v1.GetMachineCareResponse\x12{\n" +
	"\x18RunMachineCareDiagnostic\x12..cmdop.care.v1.RunMachineCareDiagnosticRequest\x1a/.cmdop.care.v1.RunMachineCareDiagnosticResponse2i\n" +
	"\x0eSessionService\x12W\n" +
	"\fListSessions\x12\".cmdop.care.v1.ListSessionsRequest\x1a#.cmdop.care.v1.ListSessionsResponseBBZ@github.com/commandoperator/cmdop-care-mcp/internal/carepb;carepbb\x06proto3"

var (
	file_proto_care_proto_rawDescOnce sync.Once
	file_proto_care_proto_rawDescData []byte
)

func file_proto_care_proto_rawDescGZIP() []byte {
	file_proto_care_proto_rawDescOnce.Do(func() {
		file_proto_care_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_care_proto_rawDesc), len(file_proto_care_proto_rawDesc)))
	})
	return file_proto_care_proto_rawDescData
}

var file_proto_care_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_care_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_proto_care_proto_goTypes = []any{
	(SessionStatus)(0),                       // 0: cmdop.care.v1.SessionStatus
	(*CareCapabilities)(nil),                 // 1: cmdop.care.v1.CareCapabilities
	(*CareFact)(nil),                         // 2: cmdop.care.v1.CareFact
	(*CareFactDomain)(nil),                   // 3: cmdop.care.v1.CareFactDomain
	(*CareFactsSnapshot)(nil),                // 4: cmdop.care.v1.CareFactsSnapshot
	(*CareStorageSource)(nil),                // 5: cmdop.care.v1.CareStorageSource
	(*CareStorageSnapshot)(nil),              // 6: cmdop.care.v1.CareStorageSnapshot
	(*CareTerminalScan)(nil),                 // 7: cmdop.care.v1.CareTerminalScan
	(*CareFinding)(nil),                      // 8: cmdop.care.v1.CareFinding
	(*CareSnapshot)(nil),                     // 9: cmdop.care.v1.CareSnapshot
	(*CareDiagnostic)(nil),                   // 10: cmdop.care.v1.CareDiagnostic
	(*CareProcessDiagnostic)(nil),            // 11: cmdop.care.v1.CareProcessDiagnostic
	(*CareProcessAttribution)(nil),           // 12: cmdop.care.v1.CareProcessAttribution
	(*CareStartupDiagnostic)(nil),            // 13: cmdop.care.v1.CareStartupDiagnostic
	(*CareStartupSource)(nil),                // 14: cmdop.care.v1.CareStartupSource
	(*CareStartupEntry)(nil),                 // 15: cmdop.care.v1.CareStartupEntry
	(*GetMachineCareRequest)(nil),            // 16: cmdop.care.v1.GetMachineCareRequest
	(*GetMachineCareResponse)(nil),           // 17: cmdop.care.v1.GetMachineCareResponse
	(*RunMachineCareDiagnosticRequest)(nil),  // 18: cmdop.care.v1.RunMachineCareDiagnosticRequest
	(*RunMachineCareDiagnosticResponse)(nil), // 19: cmdop.care.v1.RunMachineCareDiagnosticResponse
	(*SessionInfo)(nil),                      // 20: cmdop.care.v1.SessionInfo
	(*ListSessionsRequest)(nil),              // 21: cmdop.care.v1.ListSessionsRequest
	(*ListSessionsResponse)(nil),             // 22: cmdop.care.v1.ListSessionsResponse
	(*timestamppb.Timestamp)(nil),            // 23: google.protobuf.Timestamp
}
var file_proto_care_proto_depIdxs = []int32{
	2,  // 0: cmdop.care.v1.CareFactDomain.facts:type_name -> cmdop.care.v1.CareFact
	3,  // 1: cmdop.care.v1.CareFactsSnapshot.domains:type_name -> cmdop.care.v1.CareFactDomain
	5,  // 2: cmdop.care.v1.CareStorageSnapshot.sources:type_name -> cmdop.care.v1.CareStorageSource
	7,  // 3: cmdop.care.v1.CareSnapshot.latest_scan:type_name -> cmdop.care.v1.CareTerminalScan
	8,  // 4: cmdop.care.v1.CareSnapshot.findings:type_name -> cmdop.care.v1.CareFinding
	4,  // 5: cmdop.care.v1.CareSnapshot.latest_facts:type_name -> cmdop.care.v1.CareFactsSnapshot
	6,  // 6: cmdop.care.v1.CareSnapshot.latest_storage_inventory:type_name -> cmdop.care.v1.CareStorageSnapshot
	1,  // 7: cmdop.care.v1.CareSnapshot.capabilities:type_name -> cmdop.care.v1.CareCapabilities
	11, // 8: cmdop.care.v1.CareDiagnostic.processes:type_name -> cmdop.care.v1.CareProcessDiagnostic
	13, // 9: cmdop.care.v1.CareDiagnostic.startup:type_name -> cmdop.care.v1.CareStartupDiagnostic
	12, // 10: cmdop.care.v1.CareProcessDiagnostic.entries:type_name -> cmdop.care.v1.CareProcessAttribution
	14, // 11: cmdop.care.v1.CareStartupDiagnostic.sources:type_name -> cmdop.care.v1.CareStartupSource
	15, // 12: cmdop.care.v1.CareStartupSource.entries:type_name -> cmdop.care.v1.CareStartupEntry
	9,  // 13: cmdop.care.v1.GetMachineCareResponse.snapshot:type_name -> cmdop.care.v1.CareSnapshot
	10, // 14: cmdop.care.v1.RunMachineCareDiagnosticResponse.diagnostic:type_name -> cmdop.care.v1.CareDiagnostic
	0,  // 15: cmdop.care.v1.SessionInfo.status:type_name -> cmdop.care.v1.SessionStatus
	23, // 16: cmdop.care.v1.SessionInfo.connected_at:type_name -> google.protobuf.Timestamp
	23, // 17: cmdop.care.v1.SessionInfo.last_heartbeat_at:type_name -> google.protobuf.Timestamp
	23, // 18: cmdop.care.v1.SessionInfo.created_at:type_name -> google.protobuf.Timestamp
	0,  // 19: cmdop.care.v1.ListSessionsRequest.status:type_name -> cmdop.care.v1.SessionStatus
	20, // 20: cmdop.care.v1.ListSessionsResponse.sessions:type_name -> cmdop.care.v1.SessionInfo
	16, // 21: cmdop.care.v1.AiAgentService.GetMachineCare:input_type -> cmdop.care.v1.GetMachineCareRequest
	18, // 22: cmdop.care.v1.AiAgentService.RunMachineCareDiagnostic:input_type -> cmdop.care.v1.RunMachineCareDiagnosticRequest
	21, // 23: cmdop.care.v1.SessionService.ListSessions:input_type -> cmdop.care.v1.ListSessionsRequest
	17, // 24: cmdop.care.v1.AiAgentService.GetMachineCare:output_type -> cmdop.care.v1.GetMachineCareResponse
	19, // 25: cmdop.care.v1.AiAgentService.RunMachineCareDiagnostic:output_type -> cmdop.care.v1.RunMachineCareDiagnosticResponse
	22, // 26: cmdop.care.v1.SessionService.ListSessions:output_type -> cmdop.care.v1.ListSessionsResponse
	24, // [24:27] is the sub-list for method output_type
	21, // [21:24] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_proto_care_proto_init() }
func file_proto_care_proto_init() {
	if File_proto_care_proto != nil {
		return
	}
	file_proto_care_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_care_proto_rawDesc), len(file_proto_care_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_care_proto_goTypes,
		DependencyIndexes: file_proto_care_proto_depIdxs,
		EnumInfos:         file_proto_care_proto_enumTypes,
		MessageInfos:      file_proto_care_proto_msgTypes,
	}.Build()
	File_proto_care_proto = out.File
	file_proto_care_proto_goTypes = nil
	file_proto_care_proto_depIdxs = nil
}
