// Minimal wire contract for the cmdop-care MCP artifact.
//
// This is a DELIBERATELY TRIMMED subset of the private cmdop_go monorepo's
// `cmdop.agent.v1` proto package (proto/agentv1/service/{care,ai_agent,session}.proto).
// It carries only the messages and RPCs the 4 read-only tools in this
// artifact need:
//   - AiAgentService.GetMachineCare              (care_status)
//   - AiAgentService.RunMachineCareDiagnostic     (care_diagnose)
//   - SessionService.ListSessions                  (list_machines)
//
// It intentionally OMITS every mutation / exec / delegation RPC (RunAgent,
// CancelAgent, Extract, CreateSession, CloseSession, and the Care action
// propose/decision messages) — this artifact never calls them and does not
// even generate stubs for them, so there is no code path that could.
//
// Wire-compatible with the private relay: field numbers below match the
// source-of-truth proto exactly, so this client interoperates with any
// cmdop relay speaking cmdop.agent.v1, but this file is maintained here
// independently (it is not regenerated from the private monorepo).

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: proto/care.proto

package carepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AiAgentService_GetMachineCare_FullMethodName           = "/cmdop.care.v1.AiAgentService/GetMachineCare"
	AiAgentService_RunMachineCareDiagnostic_FullMethodName = "/cmdop.care.v1.AiAgentService/RunMachineCareDiagnostic"
)

// AiAgentServiceClient is the client API for AiAgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AiAgentServiceClient interface {
	// Typed, read-only last-known Care projection for one enrolled machine.
	GetMachineCare(ctx context.Context, in *GetMachineCareRequest, opts ...grpc.CallOption) (*GetMachineCareResponse, error)
	// Typed, bounded live diagnostic. The relay enforces liveness, capability,
	// policy, and the target PIN before dispatching the Care command.
	RunMachineCareDiagnostic(ctx context.Context, in *RunMachineCareDiagnosticRequest, opts ...grpc.CallOption) (*RunMachineCareDiagnosticResponse, error)
}

type aiAgentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAiAgentServiceClient(cc grpc.ClientConnInterface) AiAgentServiceClient {
	return &aiAgentServiceClient{cc}
}

func (c *aiAgentServiceClient) GetMachineCare(ctx context.Context, in *GetMachineCareRequest, opts ...grpc.CallOption) (*GetMachineCareResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMachineCareResponse)
	err := c.cc.Invoke(ctx, AiAgentService_GetMachineCare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiAgentServiceClient) RunMachineCareDiagnostic(ctx context.Context, in *RunMachineCareDiagnosticRequest, opts ...grpc.CallOption) (*RunMachineCareDiagnosticResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunMachineCareDiagnosticResponse)
	err := c.cc.Invoke(ctx, AiAgentService_RunMachineCareDiagnostic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AiAgentServiceServer is the server API for AiAgentService service.
// All implementations must embed UnimplementedAiAgentServiceServer
// for forward compatibility.
type AiAgentServiceServer interface {
	// Typed, read-only last-known Care projection for one enrolled machine.
	GetMachineCare(context.Context, *GetMachineCareRequest) (*GetMachineCareResponse, error)
	// Typed, bounded live diagnostic. The relay enforces liveness, capability,
	// policy, and the target PIN before dispatching the Care command.
	RunMachineCareDiagnostic(context.Context, *RunMachineCareDiagnosticRequest) (*RunMachineCareDiagnosticResponse, error)
	mustEmbedUnimplementedAiAgentServiceServer()
}

// UnimplementedAiAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAiAgentServiceServer struct{}

func (UnimplementedAiAgentServiceServer) GetMachineCare(context.Context, *GetMachineCareRequest) (*GetMachineCareResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMachineCare not implemented")
}
func (UnimplementedAiAgentServiceServer) RunMachineCareDiagnostic(context.Context, *RunMachineCareDiagnosticRequest) (*RunMachineCareDiagnosticResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunMachineCareDiagnostic not implemented")
}
func (UnimplementedAiAgentServiceServer) mustEmbedUnimplementedAiAgentServiceServer() {}
func (UnimplementedAiAgentServiceServer) testEmbeddedByValue()                        {}

// UnsafeAiAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AiAgentServiceServer will
// result in compilation errors.
type UnsafeAiAgentServiceServer interface {
	mustEmbedUnimplementedAiAgentServiceServer()
}

func RegisterAiAgentServiceServer(s grpc.ServiceRegistrar, srv AiAgentServiceServer) {
	// If the following call panics, it indicates UnimplementedAiAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AiAgentService_ServiceDesc, srv)
}

func _AiAgentService_GetMachineCare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMachineCareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiAgentServiceServer).GetMachineCare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiAgentService_GetMachineCare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiAgentServiceServer).GetMachineCare(ctx, req.(*GetMachineCareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiAgentService_RunMachineCareDiagnostic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunMachineCareDiagnosticRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiAgentServiceServer).RunMachineCareDiagnostic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiAgentService_RunMachineCareDiagnostic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiAgentServiceServer).RunMachineCareDiagnostic(ctx, req.(*RunMachineCareDiagnosticRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AiAgentService_ServiceDesc is the grpc.ServiceDesc for AiAgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AiAgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cmdop.care.v1.AiAgentService",
	HandlerType: (*AiAgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMachineCare",
			Handler:    _AiAgentService_GetMachineCare_Handler,
		},
		{
			MethodName: "RunMachineCareDiagnostic",
			Handler:    _AiAgentService_RunMachineCareDiagnostic_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/care.proto",
}

const (
	SessionService_ListSessions_FullMethodName = "/cmdop.care.v1.SessionService/ListSessions"
)

// SessionServiceClient is the client API for SessionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SessionServiceClient interface {
	ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error)
}

type sessionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSessionServiceClient(cc grpc.ClientConnInterface) SessionServiceClient {
	return &sessionServiceClient{cc}
}

func (c *sessionServiceClient) ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionsResponse)
	err := c.cc.Invoke(ctx, SessionService_ListSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SessionServiceServer is the server API for SessionService service.
// All implementations must embed UnimplementedSessionServiceServer
// for forward compatibility.
type SessionServiceServer interface {
	ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error)
	mustEmbedUnimplementedSessionServiceServer()
}

// UnimplementedSessionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSessionServiceServer struct{}

func (UnimplementedSessionServiceServer) ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSessions not implemented")
}
func (UnimplementedSessionServiceServer) mustEmbedUnimplementedSessionServiceServer() {}
func (UnimplementedSessionServiceServer) testEmbeddedByValue()                        {}

// UnsafeSessionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SessionServiceServer will
// result in compilation errors.
type UnsafeSessionServiceServer interface {
	mustEmbedUnimplementedSessionServiceServer()
}

func RegisterSessionServiceServer(s grpc.ServiceRegistrar, srv SessionServiceServer) {
	// If the following call panics, it indicates UnimplementedSessionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SessionService_ServiceDesc, srv)
}

func _SessionService_ListSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).ListSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionService_ListSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).ListSessions(ctx, req.(*ListSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SessionService_ServiceDesc is the grpc.ServiceDesc for SessionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SessionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cmdop.care.v1.SessionService",
	HandlerType: (*SessionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListSessions",
			Handler:    _SessionService_ListSessions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/care.proto",
}
